### ISSUE TITLE
How to config to get the trigger?

### ISSUE THREAD

**Issue by Diwahars** [hengyunabc/zabbix-api#1]
Hi,

How to config to get the trigger through java API?

Could you please give one example?

**Comment by hengyunabc** [comment]
https://www.zabbix.com/documentation/2.4/manual/api/reference/trigger/get

https://github.com/hengyunabc/zabbix-api/blob/master/src/test/java/io/github/hengyunabc/zabbix/api/test/DefaultZabbixApiTest.java

You can build a request object, with method"trigger.get", and set params.

**Comment by Diwahars** [comment]
Thanks @hengyunabc . When i try to get search for a particular description. i'm not able to get a correct output. when i compare the result its not matching up or its not fetching all data from zabbix.can you help me with an example.

Thanks in advance.

**Comment by hengyunabc** [comment]
I add a get trigger example. My zabbix version is 2.4.3.
```java
	@Test
	public void testGetTrigger() {
		boolean login = zabbixApi.login("zabbix.dev", "goK0Loqua4Eipoe");
		System.err.println("login:" + login);

		Request request = RequestBuilder.newBuilder().method("trigger.get")
				.paramEntry("triggerids", 2322).paramEntry("output", "extend")
				.paramEntry("selectFunctions", "extend").build();

		System.err.println(JSON.toJSONString(request));

		JSONObject result = zabbixApi.call(request);

		System.err.println(JSON.toJSONString(result, true));
	}
```
Output:
```javascript
{
	"id":2,
	"jsonrpc":"2.0",
	"result":[{
		"comments":"",
		"description":"Server {HOSTNAME} is unreachable for 5 minutes",
		"error":"",
		"expression":"{2549}=1 and {2550}=0",
		"flags":"0",
		"functions":[
			{
				"function":"nodata",
				"functionid":"2549",
				"itemid":"608",
				"parameter":"5m",
				"triggerid":"2322"
			},
			{
				"function":"last",
				"functionid":"2550",
				"itemid":"5958",
				"parameter":"0",
				"triggerid":"2322"
			}
		],
		"lastchange":"1438172288",
		"priority":"5",
		"state":"0",
		"status":"0",
		"templateid":"607",
		"triggerid":"2322",
		"type":"0",
		"url":"",
		"value":"0"
	}]
}
```

**Comment by Diwahars** [comment]
Thanks so much @hengyunabc . 
i just have one question. I have one scenario where i have to use "search" parameter to get the specific  trigger using "description". i want to know how it can be done here.

Thanks in advance.

**Comment by Diwahars** [comment]
And also how will you pass an array of host griup, host, items etc
