### ISSUE TITLE
Hi, Any plans to merge development branch into main?

### ISSUE THREAD

**Issue by v-zhuravlev** [hengyunabc/zabbix-api#15]
This seems to be a lot of changes there?

**Comment by hengyunabc** [comment]
Ok, version 0.0.2.

```xml
<dependency>
    <groupId>io.github.hengyunabc</groupId>
    <artifactId>zabbix-api</artifactId>
    <version>0.0.2</version>
</dependency>
```

**Comment by v-zhuravlev** [comment]
Thanks !

**Comment by v-zhuravlev** [comment]
sorry, @hengyunabc , one more thing, do you plan to publish it in maven?

**Comment by hengyunabc** [comment]
@v-zhuravlev 

http://search.maven.org/#artifactdetails%7Cio.github.hengyunabc%7Czabbix-api%7C0.0.2%7Cjar

**Comment by v-zhuravlev** [comment]
Thanks again
