### ISSUE TITLE
how to pass the array of hostid to trigger.get or event.get?

### ISSUE THREAD

**Issue by Diwahars** [hengyunabc/zabbix-api#2]
Hi,

could you help how to pass the array of hostid or itemid to trigger.get or event.get to the result for only those hostids?

thanks in advance

**Comment by hengyunabc** [comment]
https://www.zabbix.com/documentation/2.4/manual/api/reference/trigger/get

Can you try the follow code? This code is not tested.
```java
		String host = "192.168.66.29";
		List<String> hostIds = new LinkedList<String>();
		hostIds.add("1");
		hostIds.add("2");
		
		Request getRequest = RequestBuilder.newBuilder().method("trigger.get")
				.paramEntry("hostIds", hostIds).build();
```

**Comment by Diwahars** [comment]
@hengyunabc : what is the value "1" ? in the code above, it has only one host and r u trying to store that hostid in the list?

let me put it straight. i want to get the get the triggers for a particular time for a specific host. i like to use three get function here, 
hostgroup - to get the hostid from those hostgroup
Trigger - to get the trigger of the hosts from hostgroup
Event - to give a time frame for those triggerids.

i'm using java api. i have a code using zabbix php api to get the trigger from hostgroup for all hosts of that group.


PHP Code:
$groups = $api->hostgroupGet(array(
       'output' => array('name'),
       'selectHosts' => array(
               'flags',
               'hostid',
			   'itemid',
               'name',
               'maintenance_status'),
       'real_hosts ' => 1,
	   'groupids' =>  [xx,xx,xx],
	   'with_monitored_triggers' => 1,
       'sortfield' => 'name'
    ));

       foreach($groups as $group) {
               $groupIds[] = $group->groupid;
       }

       $triggers = $api->triggerGet(array(
               'output' => array(
                       'priority',
                       'description',
					   'lastChangeSince'),
			   'search' => array('description' => 'CPU above'),
               'selectHosts' => array('hostid'),
			   'selectFunctions' => array('itemid'),
               'groupids' => $groupIds,
               'expandDescription' => 1,
               'only_true' => 1,
               'monitored' => 1,
               'withLastEventUnacknowledged' => 1,
               'sortfield' => 'priority',
               'sortorder' => 'DESC'
       ));

       foreach($triggers as $trigger) {
               foreach($trigger->hosts as $host) {
                       $hostTriggers[$host->hostid][] = $trigger;
				foreach($trigger->functions as $item) {
						$Triggersfunctions[$item->itemid][] = $trigger;
               }
			   }
       }


is it possible to code like this in java? 

could you please help me in this? I need your help in this.

Please help me !

thanks in advance.

**Comment by hengyunabc** [comment]
Can you show me the php http request body? Use software like fiddler.

**Comment by Diwahars** [comment]
sure i can share that.

how that helps here?

**Comment by hengyunabc** [comment]
If you show me the http request body, I can tell you how to build the same http request in java code.

**Comment by xfworld** [comment]
@hengyunabc 我知道怎么用java代码来完成你的要求，不过我暂时没有办法公布出来；只能给你提示：
Request getRequest = RequestBuilder.newBuilder().method("trigger.get")
                .paramEntry("hostIds", hostIds).paramEntry("monitored", true).paramEntry("only_true", true).build();

try it again,best wish ^_^

**Comment by Diwahars** [comment]
@hengyunabc : is this what you looking for? 

![fiddler](https://cloud.githubusercontent.com/assets/5858395/9439990/5dcd4b74-4a89-11e5-9786-0c7e494763ba.PNG)

**Comment by hengyunabc** [comment]
Could you show the request json info?

**Comment by Diwahars** [comment]
@hengyunabc : this is my JSON Request info...

$groups = $api->hostgroupGet(array(
       'output' => array('name'),
       'selectHosts' => array(
               'flags',
               'hostid',
			   'itemid',
               'name',
               'maintenance_status'),
       'real_hosts ' => 1,
	   'groupids' =>  50,
	   //'templateids' =>['16699','16700','16701'],
       'selectTemplates' => array('name'),
	   'with_monitored_triggers' => 1,
       'sortfield' => 'name'
    ));

       foreach($groups as $group) {
               $groupIds[] = $group->groupid;
       }

       $triggers = $api->triggerGet(array(
               'output' => 'extend',
			 //  'triggerids',
			   //'value' => 1,
			 'search' => array('description' => 'Circuit Above'),
               'selectHosts' => array('hostid'),
		//	   'selectFunctions' => array('itemid'),
               'groupids' => $groupIds,
	      //  'expandDescription' => 1,
             //  'only_true' => 1,
             //  'monitored' => 1,
              // 'withLastEventUnacknowledged' => 1,
              // 'sortfield' => 'priority',
              // 'sortorder' => 'DESC'
       ));
	   
	   foreach($triggers as $trigger) {
		           $triggerIds[] = $trigger->triggerid;
				   foreach($trigger->hosts as $host) {
                       $hostTriggers[$host->hostid][] = $trigger;
				   }
			   }
$events = $api->eventGet(array(
					'output' => 'extend',
					'objectids' => $triggerIds,
					'value' => 1
				//	'time_from' => '1437350400',
				//	'time_till' => '1438128000'
					));	   
	   
echo json_encode($events);

how to write the above request in java?

**Comment by hengyunabc** [comment]
Sorry, I know little about php.
Could you show me this tab?
![zabbix-http](https://cloud.githubusercontent.com/assets/1683936/9487019/89b7e276-4c00-11e5-9676-4b35c55be591.png)

**Comment by Diwahars** [comment]
@hengyunabc : i didnt get anything in that tab.

I will explain my requirement:

-> I want to get the host of a particular hostgroup. For that i have to give the hostgroup and get the hostids from the group.

-> these hostids have to passed in an array to the trigger.get, where we search for a particular description and get those triggerids.

->pass those triggerids inan array to event.get, where we give a specific time frame to get the events from zabbix.

Could you please help me in building this flow using java api??

Awaiting your reply!

**Comment by hengyunabc** [comment]
The php code is written by you? Could you post this output?
```php
echo json_encode($events);
```

**Comment by Diwahars** [comment]
This is the output of json_encode($events):
[
{
eventid: "1241351",
source: "0",
object: "0",
objectid: "17287",
clock: "1438053742",
value: "1",
acknowledged: "0",
ns: "284259138"
},
{
eventid: "1241525",
source: "0",
object: "0",
objectid: "17287",
clock: "1438069882",
value: "1",
acknowledged: "0",
ns: "200433666"
},
{
eventid: "1241491",
source: "0",
object: "0",
objectid: "34514",
clock: "1438066541",
value: "1",
acknowledged: "0",
ns: "240015363"
},
{
eventid: "1241562",
source: "0",
object: "0",
objectid: "34514",
clock: "1438073741",
value: "1",
acknowledged: "0",
ns: "426604032"
},
{
eventid: "1241577",
source: "0",
object: "0",
objectid: "34514",
clock: "1438075001",
value: "1",
acknowledged: "0",
ns: "708544766"
},
{
eventid: "1241565",
source: "0",
object: "0",
objectid: "34515",
clock: "1438073861",
value: "1",
acknowledged: "0",
ns: "638531529"
},
{
eventid: "1241905",
source: "0",
object: "0",
objectid: "34515",
clock: "1438103861",
value: "1",
acknowledged: "0",
ns: "116692092"
},
{
eventid: "1241241",
source: "0",
object: "0",
objectid: "34516",
clock: "1438046578",
value: "1",
acknowledged: "0",
ns: "66029505"
},
{
eventid: "1241311",
source: "0",
object: "0",
objectid: "34516",
clock: "1438050778",
value: "1",
acknowledged: "0",
ns: "377082314"
}
]

**Comment by hengyunabc** [comment]
Output these?
```php
array(
'output' => array('name'),
'selectHosts' => array(
'flags',
'hostid',
'itemid',
'name',
'maintenance_status'),
'real_hosts ' => 1,
'groupids' => 50,
//'templateids' =>['16699','16700','16701'],
'selectTemplates' => array('name'),
'with_monitored_triggers' => 1,
'sortfield' => 'name'
)
```

```php
array(
'output' => 'extend',
'objectids' => $triggerIds,
'value' => 1
// 'time_from' => '1437350400',
// 'time_till' => '1438128000'
)
```

**Comment by Diwahars** [comment]
you want output of hostgroup and event separately?

**Comment by hengyunabc** [comment]
I just want to know the request body content.

**Comment by Diwahars** [comment]
Request body content means, you want to know the which parameter are passed in request?

Sorry if i misunderstand your question?

**Comment by hengyunabc** [comment]
The http request body contains the json object, I want to know the json object content.
![http-request](https://cloud.githubusercontent.com/assets/1683936/9490183/c23d172a-4c18-11e5-8fd4-7bb978eda5f7.png)

**Comment by hengyunabc** [comment]
So I want to know what object you pass to the php api.
```php
$groups = $api->hostgroupGet(object)
```
Could you print the object with json format?

**Comment by Diwahars** [comment]
for php there is a PHP class library available to communicate with the Zabbix. 

below is the php class library github repo:
https://github.com/confirm-it-solutions/PhpZabbixApi

this is object im passing in php api:
array(
'output' => array('name'),
'selectHosts' => array(
'flags',
'hostid',
'itemid',
'name',
'maintenance_status'),
'real_hosts ' => 1,
'groupids' => 50,
//'templateids' =>['16699','16700','16701'],
'selectTemplates' => array('name'),
'with_monitored_triggers' => 1,
'sortfield' => 'name'
)

you want the above object in json format?

**Comment by Diwahars** [comment]
@hengyunabc can u help in above ask?

**Comment by hengyunabc** [comment]
I found one json response object from this page: https://www.zabbix.com/documentation/2.4/manual/api/reference/host/get
```javascript
{
    "jsonrpc": "2.0",
    "result": [
        {
            "hostid": "10084",
            "host": "Zabbix server",
            "inventory": {
                "os": "Linux Ubuntu"
            }
        },
        {
            "hostid": "10107",
            "host": "Linux server",
            "inventory": {
                "os": "Linux Mint"
            }
        }
    ],
    "id": 1
}
```
You can process it like this:
```java
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;

public class Test {

	public static void main(String[] args) {
		String responseString = "{\"jsonrpc\": \"2.0\",\"result\": [{\"hostid\": \"10084\","
				+ "\"host\": \"Zabbix server\",\"inventory\": {\"os\": \"Linux Ubuntu\"}},"
				+ "{\"hostid\": \"10107\",\"host\": \"Linux server\",\"inventory\": {\"os\": \"Linux Mint\"}}],\"id\": 1}";

		JSONObject response = JSON.parseObject(responseString);
		JSONArray result = response.getJSONArray("result");
		
		JSONObject host = result.getJSONObject(0);
		
		int hostid = host.getIntValue("hostid");
		String hostName = host.getString("host");
		
		System.err.println("hostid:" + hostid);
		System.err.println("host:" + hostName);
	}

}
```
