### ISSUE TITLE
Passing the response as an array?

### ISSUE THREAD

**Issue by Diwahars** [hengyunabc/zabbix-api#3]
Hi @hengyunabc ,

is there a way to pass the json response to an array and then pass those array to the next function?

**Comment by hengyunabc** [comment]
Which api will return a json array?

**Comment by hengyunabc** [comment]
According to the document, I found that all response is a json object:
```javascript
{
    "jsonrpc": "2.0",
    "result": [
        ...
    ],
    "id": 1
}
```

**Comment by Diwahars** [comment]
@hengyunabc 

the response is 
{"id":2,"jsonrpc":"2.0","result":[{"flags":"0","groupid":"50","hosts":[{"hostid":"10337","name":"ss"},{"hostid":"10805","name":"dd"},{"hostid":"10806","name":"dd"},,"internal":"0","name":"aaaa"},{"flags":"0","groupid":"54","hosts":[{"hostid":"10225","name":"xxx"},{"hostid":"10304","name":"yyy"},"internal":"0","name":"bbbb"}]}

How to pass this jsonobject into a array and get all the hostid ??

**Comment by hengyunabc** [comment]
I found one json response object from this page: https://www.zabbix.com/documentation/2.4/manual/api/reference/host/get
```javascript
{
    "jsonrpc": "2.0",
    "result": [
        {
            "hostid": "10084",
            "host": "Zabbix server",
            "inventory": {
                "os": "Linux Ubuntu"
            }
        },
        {
            "hostid": "10107",
            "host": "Linux server",
            "inventory": {
                "os": "Linux Mint"
            }
        }
    ],
    "id": 1
}
```
You can process it like this:
```java
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;

public class Test {

	public static void main(String[] args) {
		String responseString = "{\"jsonrpc\": \"2.0\",\"result\": [{\"hostid\": \"10084\","
				+ "\"host\": \"Zabbix server\",\"inventory\": {\"os\": \"Linux Ubuntu\"}},"
				+ "{\"hostid\": \"10107\",\"host\": \"Linux server\",\"inventory\": {\"os\": \"Linux Mint\"}}],\"id\": 1}";

		JSONObject response = JSON.parseObject(responseString);
		JSONArray result = response.getJSONArray("result");
		
		JSONObject host = result.getJSONObject(0);
		
		int hostid = host.getIntValue("hostid");
		String hostName = host.getString("host");
		
		System.err.println("hostid:" + hostid);
		System.err.println("host:" + hostName);
	}

}
```

**Comment by Diwahars** [comment]
@hengyunabc 

Thanks for the response!

how to use "search" attribute in json request builder? can you show one example for that??

For example: I found this from 
https://www.zabbix.com/documentation/2.4/manual/api/reference/item/get

{
    "jsonrpc": "2.0",
    "method": "item.get",
    "params": {
        "output": "extend",
        "hostids": "10084",
        "search": {
            "key_": "system"
        },
        "sortfield": "name"
    },
    "auth": "038e1d7b1735c6a5436ee9eae095879e",
    "id": 1
}

for this the request builder would be:
Request request = RequestBuilder.newBuilder().method("item.get")
				.paramEntry("hostids", 10084).paramEntry("output", "extend")
				.paramEntry("sortfield", "name").build();

how to use the  search attribute here??

**Comment by hengyunabc** [comment]
```java
Map search = new HashMap();
search.put("key_", "system");
Request request = RequestBuilder.newBuilder().method("item.get")
.paramEntry("search", search)
```
or
```java
JSONObject search = new JSONObject()
search.put("key_", "system");
```

**Comment by Diwahars** [comment]
Thank you very much @hengyunabc .
