### ISSUE TITLE
set loglevel to WARN

### ISSUE THREAD

**Issue by akosyrev** [hengyunabc/zabbix-api#5]
Hello. 
Thank you for that lib!
I'd like to set loglevel for org.apache.http.*, but i don't know how - i'm far from programming in java(
Can you help me?

**Comment by hengyunabc** [comment]
If you use log4j, in your log4j.properties:
```
log4j.logger.org.apache.http=INFO
```
If you use logback, in your logback.xml
```xml
<logger name="org.apache.http" level="INFO" />
```
