### ISSUE TITLE
How to optimize the execution time??

### ISSUE THREAD

**Issue by Diwahars** [hengyunabc/zabbix-api#6]
Hi @hengyunabc ,

I'm trying to get a particular trigger by searching for a specific description for a given time frame.

I have configured to get trigger for a particular description and Getting these triggers for a given time, the time limit in trigger function is not giving desired output. So to get the trigger for a given time, we have to use event.get
When we pass these json array to each function and the logic I defined using java, it takes time to get the data and performance is also affected. 

Could you please help or guide me, how to optimize the code to reduce the execution time?

**Comment by hengyunabc** [comment]
You need that the zabbix server take a long time to return the search result?

Try to cache the search result?

Maybe you can get help in zabbix form. https://www.zabbix.com/forum/

**Comment by Diwahars** [comment]
@hengyunabc 

Server is not taking time. it's taking time, because of the request.

I have approached like getting hostid from hostgroup.get and passing those values in an array and passing those array of hostid to trigger.get and searching for particular description., getting the trigger id for that description in an array and passing that to event.get to get the triggers for a specific time.
i have approx 400 hosts and loop takes more time to execute. I'm asking whether its possible to optimize the loop or something else?

Please find the logic below:
int groupid[]= {groupids};
String selectHosts[] = { "hostid", "name"};
		Request getHost = RequestBuilder.newBuilder().version(jsonrpc)
				.method("host.get")
				.paramEntry("groupids", groupid)
				.paramEntry("with_monitored_triggers", 1)
				//.paramEntry("monitored_hosts",1)
				.paramEntry("output", selectHosts).build();
		
		JSONObject getResponse = zabbixApi.call(getHost);
		System.out.println("get host : " + getHost);
		System.out.println("get response : " + getResponse);
		
		// Array to get oly the Hostids
		JSONObject Hostmyjson = new JSONObject(getResponse);
		JSONArray Host_json_array = Hostmyjson.getJSONArray("result");
				
		int size = Host_json_array.size();
	//	System.out.println(size);
		ArrayList<String> Hostarrays = new ArrayList<String>();
		String hostid;
		for (int i = 0; i < size; i++) {
			
	    //	JSONObject Host = null;
	    	JSONObject Host = Host_json_array.getJSONObject(i); // it has one array
	    	hostid = Host.getString("hostid");
	    	
	    	System.out.println(hostid); 
		
		
		/* trigger*/
		// Trigger Search Definition
		Map search = new HashMap();
		search.put("description", "XXX");
		String hostop[] = {"hostid","name"};
		String triggerop[] = {"hostids","triggerid","priority", "description"};
	
		Request getTrigger = RequestBuilder.newBuilder().version(jsonrpc)
				.method("trigger.get").id(id).auth(authCode)
				.paramEntry("hostids", hostid) // Hostids got from the array
				.paramEntry("output", triggerop)
				.paramEntry("search", search)
				.build();

		System.out.println("get trigger" + getTrigger);
		JSONObject getTriggerResponse = zabbixApi.call(getTrigger);
		System.out.println("Trigger Response :" + getTriggerResponse);
		
		// Array to get oly the Triggerids
		JSONObject myjson = new JSONObject(getTriggerResponse);
		JSONArray the_json_array = myjson.getJSONArray("result");
			
		int Triggersize = the_json_array.size();
	//	System.out.println(Triggersize);
		ArrayList<String> arrays = new ArrayList<String>();
		
		for (int j = 0; j < Triggersize; j++) {
			JSONObject o = the_json_array.getJSONObject(j); 
	    	String triggerid = o.getString("triggerid");
	    	
	    	System.out.println(triggerid);   
	  		
		/* Events */
		String triggerop1[] = {"hostid","priority"};
		
		Request request1 = RequestBuilder.newBuilder().method("event.get")
				.paramEntry("output", "extend")
				.paramEntry("objectids", triggerid)
				.paramEntry("value", 1)
			//	.paramEntry("time_from", 1441065600)
			//	.paramEntry("time_till", 1441756799)
				.build();

		System.err.println(JSON.toJSONString(request1));

		JSONObject result = zabbixApi.call(request1);

		System.err.println(JSON.toJSONString(result, true));
		}
		}

is there a way to optimize this?

**Comment by hengyunabc** [comment]
Why you do not search all the hosts in one request?
```java
List<String> hostIds = new ListedList<String>();
//put add hostId into hostIds
...

.paramEntry("hostids", hostIds) // all hosts
```

**Comment by Diwahars** [comment]
@hengyunabc 

instead of Arraylist your suggesting to use "List". if we use list no need for loop?

could you u edit n show one example?

**Comment by hengyunabc** [comment]
Sorry, It should be ````LinkedList<String>````.

**Comment by Diwahars** [comment]
After getting it in linkedlist... V ve to send in loop rt?

**Comment by hengyunabc** [comment]
```java
JSONObject getResponse = zabbixApi.call(getHost);
JSONArray<JSONObject> hostJSONArray = getResponse.getJSONArray("result");

List<String> hostIdList = new ArrayList<String>();

for(JSONObject hostInfo : hostJSONArray){
	String hostId = hostInfo.getString("hostid");
	hostIdList.add(hostId);
}
...

Request getTrigger = RequestBuilder.newBuilder().version(jsonrpc)
            .method("trigger.get").id(id).auth(authCode)
            .paramEntry("hostids", hostIdList) // all Hosts
            .paramEntry("output", triggerop)
            .paramEntry("search", search)
            .build();
```

**Comment by Diwahars** [comment]
@hengyunabc 

Still the same result. it takes time to execute and give the o/p. :(
