### ISSUE TITLE
想通过调用api来收集数据（调用sender发送数据到server）但是无法调通。

### ISSUE THREAD

**Issue by zh-lizhi** [hengyunabc/zabbix-api#8]
你好，下载了zabbix-api，api-master和sender-master但是按照readme和test测试无法调用api。
测试api-master和sender-master都无法调通……

**Comment by hengyunabc** [comment]
你可以先试下zabbix-api login，看能不能成功？

如果你没有zabbix-server，则可以运行那个docker版本的。

另外，api-master和sender-master，这两个是什么库？

**Comment by zh-lizhi** [comment]
api-master和sender-master
是zabbix-sender-master，zabbix-api-master，都是从这里下载的。
zabbix-api login无法登陆，zabbix部署在阿里云上面再（是不是防火墙什么的问题？），我在本机eclipse下尝试调用api，
	public static void main(String[] args) {
		
		DefaultZabbixApiTest dt = new DefaultZabbixApiTest();
		dt.before();
		dt.testLogin();
		//dt.testVersion();
		
		dt.after();
	}
------------------  报如下错误---------------------
09:10:59.360 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://120.26.141.51:10051][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
Exception in thread "main" java.lang.RuntimeException: DefaultZabbixApi call exception!
	at io.github.hengyunabc.zabbix.api.DefaultZabbixApi.call(DefaultZabbixApi.java:147)
	at io.github.hengyunabc.zabbix.api.DefaultZabbixApi.login(DefaultZabbixApi.java:74)
	at io.github.hengyunabc.zabbix.api.test.DefaultZabbixApiTest.testLogin(DefaultZabbixApiTest.java:42)
	at io.github.hengyunabc.zabbix.api.test.DefaultZabbixApiTest.main(DefaultZabbixApiTest.java:57)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at io.github.hengyunabc.zabbix.api.DefaultZabbixApi.call(DefaultZabbixApi.java:142)
	... 3 more

**Comment by zh-lizhi** [comment]
调试，问题出在这一行……麻烦给看看
HttpUriRequest httpRequest = org.apache.http.client.methods.RequestBuilder
					.post().setUri(uri)
					.addHeader("Content-Type", "application/json")
					.setEntity(new StringEntity(JSON.toJSONString(request)))
					.build();

**Comment by hengyunabc** [comment]
如果是在阿里云上里，先确认你的端口是不是开放的。用telnet，或者直接浏览器打开ip + 端口。

如果浏览器可以正常地登陆，那么zabbix-api也应该可以正常地login成功。

**Comment by zh-lizhi** [comment]
http://120.26.141.51:10051/zabbix/api_jsonrpc.php
提示ok

**Comment by hengyunabc** [comment]
你的版本太低了，升级到2.4以上的吧。2.2的登陆的参数和2.4的不一样。
https://www.zabbix.com/documentation/2.2/manual/api/reference/user/login

**Comment by zh-lizhi** [comment]
请问您提供的api是基于哪本版本的？
2.4以上都兼容该api吗？

**Comment by hengyunabc** [comment]
我在实现的时候，参考的是2.4的API。只能保证在2.4是可以正常运行的。
https://www.zabbix.com/documentation/2.4/manual/api/reference/user/login

**Comment by zh-lizhi** [comment]
zabbix 已升级到2.4


http://120.26.141.51:10051/zabbix/api_jsonrpc.php
提示ok
http://120.26.141.51
默认用户名/密码，你可以上去看下

我在本机eclipse下尝试调用api，
public static void main(String[] args) {

    DefaultZabbixApiTest dt = new DefaultZabbixApiTest();
    dt.before();
    dt.testLogin();
    //dt.testVersion();

    dt.after();
}
-----------------------      报错如下   ------------------------
17:11:58.300 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://120.26.141.51:10051][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
Exception in thread "main" java.lang.RuntimeException: DefaultZabbixApi call exception!
	at io.github.hengyunabc.zabbix.api.DefaultZabbixApi.call(DefaultZabbixApi.java:147)
	at io.github.hengyunabc.zabbix.api.DefaultZabbixApi.login(DefaultZabbixApi.java:74)
	at io.github.hengyunabc.zabbix.api.test.DefaultZabbixApiTest.testLogin(DefaultZabbixApiTest.java:42)
	at io.github.hengyunabc.zabbix.api.test.DefaultZabbixApiTest.main(DefaultZabbixApiTest.java:57)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at io.github.hengyunabc.zabbix.api.DefaultZabbixApi.call(DefaultZabbixApi.java:142)
	... 3 more
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 6 more
具体报错行
DefaultZabbixApi.java
CloseableHttpResponse response = httpClient.execute(httpRequest);

httpRequest： POST http://120.26.141.51:10051/zabbix/api_jsonrpc.php HTTP/1.1
entity：[Content-Type: text/plain; charset=ISO-8859-1,Content-Length: 92,Chunked: false]

**Comment by hengyunabc** [comment]
你的zabbix服务器返回数据有问题，无论发送什么过去，都是返回一个ok。你抓包就可以发现了。

**Comment by zh-lizhi** [comment]
是的，都返回ok，这个问题怎么解决呢？是zabbix-server哪里配置有问题吗？

17:01:12.082 [main] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: best-match
17:01:12.092 [main] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
17:01:12.092 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://120.26.141.51:10051][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
17:01:12.112 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://120.26.141.51:10051][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
17:01:12.112 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {}->http://120.26.141.51:10051
17:01:12.112 [main] DEBUG o.a.h.i.c.HttpClientConnectionOperator - Connecting to /120.26.141.51:10051
17:01:12.132 [main] DEBUG o.a.h.i.c.HttpClientConnectionOperator - Connection established 10.26.30.45:59207<->120.26.141.51:10051
17:01:12.132 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request POST /zabbix/api_jsonrpc.php HTTP/1.1
17:01:12.132 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
17:01:12.132 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
17:01:12.132 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> POST /zabbix/api_jsonrpc.php HTTP/1.1
17:01:12.132 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: application/json
17:01:12.132 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 92
17:01:12.132 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: 120.26.141.51:10051
17:01:12.132 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
17:01:12.132 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
17:01:12.132 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
17:01:12.132 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /zabbix/api_jsonrpc.php HTTP/1.1[\r][\n]"
17:01:12.132 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
17:01:12.132 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 92[\r][\n]"
17:01:12.132 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: 120.26.141.51:10051[\r][\n]"
17:01:12.132 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
17:01:12.132 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.3.6 (java 1.5)[\r][\n]"
17:01:12.132 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
17:01:12.132 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
17:01:12.132 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "{"id":1,"jsonrpc":"2.0","method":"user.login","params":{"password":"zabbix","user":"admin"}}"
17:01:12.152 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "OK"
17:01:12.152 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "end of stream"
17:01:12.152 [main] DEBUG o.a.h.i.c.DefaultHttpResponseParser - Garbage in response: OK
17:01:12.152 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "end of stream"
17:01:12.152 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
17:01:12.152 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
17:01:12.152 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
17:01:12.152 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
17:01:12.152 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://120.26.141.51:10051][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
Exception in thread "main" java.lang.RuntimeException: DefaultZabbixApi call exception!
	at io.github.hengyunabc.zabbix.api.DefaultZabbixApi.call(DefaultZabbixApi.java:157)
	at io.github.hengyunabc.zabbix.api.DefaultZabbixApi.login(DefaultZabbixApi.java:73)
	at io.github.hengyunabc.zabbix.api.test.DefaultZabbixApiTest.testLogin(DefaultZabbixApiTest.java:48)
	at io.github.hengyunabc.zabbix.api.test.DefaultZabbixApiTest.main(DefaultZabbixApiTest.java:63)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at io.github.hengyunabc.zabbix.api.DefaultZabbixApi.call(DefaultZabbixApi.java:144)
	... 3 more
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 6 more

**Comment by hengyunabc** [comment]
这个只能慢慢排查了。
可以试下直接到你的云机器上，用curl来构造请求，看下能不能正常返回JSON格式的数据。
也有可能是zabbix的帐号没有开通api的功能？（纯猜测）

建议你试下那个zabbix的docker镜像。

**Comment by zh-lizhi** [comment]
curl可以正常调用如下：
[root@iZ23jhe29j3Z ~]# curl -i -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":
> "2.0","method":"user.login","params":{"user":"admin","password":"zabbix"},"auth":
> null,"id":0}' http://120.26.141.51/api_jsonrpc.php
HTTP/1.1 200 OK
Server: nginx/1.0.15
Date: Thu, 26 Nov 2015 09:39:54 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.3.3
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000

{"jsonrpc":"2.0","result":"bcd6044f0e0594c2a9302f559e1f737e","id":0}
[root@iZ23jhe29j3Z ~]# 

参考上面的curl我觉得问题可能出在这一行
		String url = "http://120.26.141.51:10051/zabbix/api_jsonrpc.php";
应该修改为：String url = "http://120.26.141.51/api_jsonrpc.php";
然后就可以调通啦
log如下：
17:41:08.103 [main] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: best-match
17:41:08.123 [main] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
17:41:08.123 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://120.26.141.51:80][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
17:41:08.143 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://120.26.141.51:80][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
17:41:08.143 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {}->http://120.26.141.51:80
17:41:08.143 [main] DEBUG o.a.h.i.c.HttpClientConnectionOperator - Connecting to /120.26.141.51:80
17:41:08.163 [main] DEBUG o.a.h.i.c.HttpClientConnectionOperator - Connection established 10.26.30.45:50672<->120.26.141.51:80
17:41:08.163 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request POST /api_jsonrpc.php HTTP/1.1
17:41:08.163 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
17:41:08.163 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
17:41:08.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> POST /api_jsonrpc.php HTTP/1.1
17:41:08.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: application/json
17:41:08.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 92
17:41:08.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: 120.26.141.51
17:41:08.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
17:41:08.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
17:41:08.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
17:41:08.173 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /api_jsonrpc.php HTTP/1.1[\r][\n]"
17:41:08.173 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
17:41:08.173 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 92[\r][\n]"
17:41:08.173 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: 120.26.141.51[\r][\n]"
17:41:08.173 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
17:41:08.173 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.3.6 (java 1.5)[\r][\n]"
17:41:08.173 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
17:41:08.173 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
17:41:08.173 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "{"id":1,"jsonrpc":"2.0","method":"user.login","params":{"password":"zabbix","user":"admin"}}"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Server: nginx/1.0.15[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Thu, 26 Nov 2015 09:41:05 GMT[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Powered-By: PHP/5.3.3[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Origin: *[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Headers: Content-Type[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Methods: POST[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Max-Age: 1000[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "44[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "{"jsonrpc":"2.0","result":"b9879911f389d926bc5098c646d170fc","id":1}[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "0[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: nginx/1.0.15
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Thu, 26 Nov 2015 09:41:05 GMT
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: application/json
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Transfer-Encoding: chunked
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Connection: keep-alive
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Powered-By: PHP/5.3.3
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Origin: *
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Headers: Content-Type
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Methods: POST
17:41:08.243 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Max-Age: 1000
17:41:08.253 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
17:41:08.253 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection [id: 0][route: {}->http://120.26.141.51:80] can be kept alive indefinitely
17:41:08.253 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://120.26.141.51:80][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
17:41:08.253 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Cancelling request execution
login result:true
17:41:08.273 [main] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: best-match
17:41:08.273 [main] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
17:41:08.273 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://120.26.141.51:80][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
17:41:08.273 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://120.26.141.51:80][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
17:41:08.273 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Stale connection check
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[read] I/O error: Read timed out"
17:41:08.283 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request POST /api_jsonrpc.php HTTP/1.1
17:41:08.283 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
17:41:08.283 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
17:41:08.283 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> POST /api_jsonrpc.php HTTP/1.1
17:41:08.283 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: application/json
17:41:08.283 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 115
17:41:08.283 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: 120.26.141.51
17:41:08.283 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
17:41:08.283 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
17:41:08.283 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /api_jsonrpc.php HTTP/1.1[\r][\n]"
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 115[\r][\n]"
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: 120.26.141.51[\r][\n]"
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.3.6 (java 1.5)[\r][\n]"
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
17:41:08.283 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "{"auth":"b9879911f389d926bc5098c646d170fc","id":2,"jsonrpc":"2.0","method":"user.get","params":{"output":"extend"}}"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Server: nginx/1.0.15[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Thu, 26 Nov 2015 09:41:05 GMT[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Powered-By: PHP/5.3.3[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Origin: *[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Headers: Content-Type[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Allow-Methods: POST[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Access-Control-Max-Age: 1000[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "221[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "{"jsonrpc":"2.0","result":[{"userid":"1","alias":"Admin","name":"Zabbix","surname":"Administrator","url":"","autologin":"1","autologout":"0","lang":"zh_CN","refresh":"30","type":"3","theme":"default","attempt_failed":"0","attempt_ip":"59.174.162.202","attempt_clock":"1448523743","rows_per_page":"50"},{"userid":"2","alias":"guest","name":"","surname":"","url":"","autologin":"0","autologout":"900","lang":"en_GB","refresh":"30","type":"1","theme":"default","attempt_failed":"0","attempt_ip":"","attempt_clock":"0","rows_per_page":"50"}],"id":2}[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "0[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: nginx/1.0.15
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Thu, 26 Nov 2015 09:41:05 GMT
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: application/json
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Transfer-Encoding: chunked
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Connection: keep-alive
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Powered-By: PHP/5.3.3
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Origin: *
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Headers: Content-Type
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Allow-Methods: POST
17:41:08.343 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Access-Control-Max-Age: 1000
17:41:08.343 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
17:41:08.343 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection [id: 0][route: {}->http://120.26.141.51:80] can be kept alive indefinitely
17:41:08.343 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://120.26.141.51:80][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
17:41:08.343 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Cancelling request execution
{
	"id":2,
	"jsonrpc":"2.0",
	"result":[
		{
			"alias":"Admin",
			"attempt_clock":"1448523743",
			"attempt_failed":"0",
			"attempt_ip":"59.174.162.202",
			"autologin":"1",
			"autologout":"0",
			"lang":"zh_CN",
			"name":"Zabbix",
			"refresh":"30",
			"rows_per_page":"50",
			"surname":"Administrator",
			"theme":"default",
			"type":"3",
			"url":"",
			"userid":"1"
		},
		{
			"alias":"guest",
			"attempt_clock":"0",
			"attempt_failed":"0",
			"attempt_ip":"",
			"autologin":"0",
			"autologout":"900",
			"lang":"en_GB",
			"name":"",
			"refresh":"30",
			"rows_per_page":"50",
			"surname":"",
			"theme":"default",
			"type":"1",
			"url":"",
			"userid":"2"
		}
	]
}
17:41:08.353 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection manager is shutting down
17:41:08.353 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
17:41:08.353 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
17:41:08.353 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection manager shut down

**Comment by zh-lizhi** [comment]
非常感谢……
